config/routes.rb
Projektni::Application.routes.draw do
  devise_for :users

  resources :glasses

end

app/models/glass.rb
class Glass < ActiveRecord::Base
  attr_accessible :description, :factor, :price, :title, :company, :photo

  has_attached_file :photo

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpg' , 'image/jpeg' , 'image/png']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/glasses_controller.rb
class GlassesController < ApplicationController

  before_filter :authenticate_user!
  # GET /glasses
  # GET /glasses.json
  def index
    @glasses = Glass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @glasses }
    end
  end

  # GET /glasses/1
  # GET /glasses/1.json
  def show
    @glass = Glass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @glass }
    end
  end

  # GET /glasses/new
  # GET /glasses/new.json
  def new
    @glass = Glass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @glass }
    end
  end

  # GET /glasses/1/edit
  def edit
    @glass = Glass.find(params[:id])
  end

  # POST /glasses
  # POST /glasses.json
  def create
    @glass = Glass.new(params[:glass])

    respond_to do |format|
      if @glass.save
        format.html { redirect_to @glass, notice: 'Glass was successfully created.' }
        format.json { render json: @glass, status: :created, location: @glass }
      else
        format.html { render action: "new" }
        format.json { render json: @glass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /glasses/1
  # PUT /glasses/1.json
  def update
    @glass = Glass.find(params[:id])

    respond_to do |format|
      if @glass.update_attributes(params[:glass])
        format.html { redirect_to @glass, notice: 'Glass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @glass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glasses/1
  # DELETE /glasses/1.json
  def destroy
    @glass = Glass.find(params[:id])
    @glass.destroy

    respond_to do |format|
      format.html { redirect_to glasses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glasses_helper.rb
module GlassesHelper
end

app/views/glasses/_form.html.erb
<%= form_for @glass, :html => {:multipart => true} do |f| %>
  <% if @glass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@glass.errors.count, "error") %> prohibited this glass from being saved:</h2>

      <ul>
      <% @glass.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
      <%= f.label :company %><br />
      <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :factor %><br />
    <%= f.number_field :factor %>
  </div>
    <div class="field">
      <%= f.label :photo %><br />
      <%= f.file_field :photo %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/glasses/edit.html.erb
<h1>Editing glass</h1>

<%= render 'form' %>

<%= link_to 'Show', @glass %> |
<%= link_to 'Back', glasses_path %>

app/views/glasses/index.html.erb
<div>
  <%= link_to "sign_out", destroy_user_session_path, method: :delete %>

</div>




<h1>Listing glasses</h1>


<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Company</th>
    <th>Price</th>
    <th>Factor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @glasses.each do |glass| %>
  <tr>
    <td><%= glass.title %></td>
    <td><%= glass.description %></td>
    <td><%= glass.company %></td>
    <td><%= glass.price %></td>
    <td><%= glass.factor %></td>
    <td><%= link_to 'Show', glass %></td>
    <td><%= link_to 'Edit', edit_glass_path(glass) %></td>
    <td><%= link_to 'Destroy', glass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Glass', new_glass_path %>

app/views/glasses/new.html.erb
<h1>New glass</h1>

<%= render 'form' %>

<%= link_to 'Back', glasses_path %>

app/views/glasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @glass.title %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @glass.photo.url %>
</p>

<p>
  <b>Company:</b>
  <%= @glass.company %>
</p>

<p>
  <b>Description:</b>
  <%= @glass.description %>
</p>

<p>
  <b>Price:</b>
  <%= @glass.price %>
</p>

<p>
  <b>Factor:</b>
  <%= @glass.factor %>
</p>


<%= link_to 'Edit', edit_glass_path(@glass) %> |
<%= link_to 'Back', glasses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <meta charset="utf-8" /><title>Projektni</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper"><!-- #wrapper -->



  <header><!-- header -->

    <h1><a href="#">OČALA</a></h1>
    <h2>Your cute and compelling tag line goes here</h2>
  </header><!-- end of header -->
  <section id="main"><!-- #main content and sidebar area -->
<%= yield %>
  </section><!-- end of #content -->

  <aside id="sidebar"><!-- sidebar -->







  </aside><!-- end of sidebar -->

  </section><!-- end of #main content and sidebar-->

  <footer>
    <section id="footer-area">

      <section id="footer-outer-block">
        <aside class="footer-segment">


        </aside><!-- end of #first footer segment -->

        <aside class="footer-segment">


        </aside><!-- end of #second footer segment -->

        <aside class="footer-segment">


        </aside><!-- end of #third footer segment -->

        <aside class="footer-segment">

        </aside><!-- end of #fourth footer segment -->

      </section><!-- end of footer-outer-block -->

    </section><!-- end of footer-area -->
  </footer>

</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>

</body>
</html>